services:
  - type: web
    name: sentiment-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_MODEL_NAME
        value: YOUR_HF_USERNAME/sentiment-bert-model   # ← غيّري هذا
      - key: PYTHON_VERSION
        value: 3.10.0
